#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

datadir=${dir}/db

# Test 1 seed
# amitMn6C5ofDxGBnZy5Gcmdh7Wcge7zRJMJw2ZpbTxP1PxLQeCawxRNYpbdLiwcSuA9YACZEFxkWNWnFYzJ1Kocd26jPvU4Qbb
# tell jump fibula hounded nestle suitcase elapse comb vials syllabus evolved butter bobsled taken fishing pavements beyond ahead slug slug chrome echo bays bowling fibula

# Test 2 seed
# amitMREjMaV8wvj5RTjuSD5ksbjHnoXMaK89UjT9utZ5W6tE8N3UsZSVdeStYogWw93o88QnN3rMK68GK1KbhERzA5SRqEyrHM
# lodge erected logic giant hookup losing deftly unwind tomorrow richly elbow observant sizes erosion feel tadpoles intended cigar upwards does aerial tobacco bifocals cousin bifocals

function wallet1()
{
	rm -f ${dir}/t1.cache
	${dir}/builder/build/dev/debug/bin/amity-wallet-cli --stagenet --daemon-address 127.0.0.1:28081 --wallet-file ${dir}/t1 --password ""
}

function wallet2()
{
	rm -f ${dir}/t2.cache
	${dir}/builder/build/dev/debug/bin/amity-wallet-cli --stagenet --daemon-address 127.0.0.1:38081 --wallet-file ${dir}/t2 --password ""
}

function n1()
{
	${dir}/builder/build/dev/debug/bin/amityd --stagenet --data-dir ${datadir}/n1 --p2p-bind-port 28080 --rpc-bind-port 28081 --zmq-rpc-bind-port 28082 --rpc-restricted-bind-port 28083 \
	--add-exclusive-node 127.0.0.1:38080 \
	--fixed-difficulty ${DIFF} --block-sync-size 10
}

function n2()
{
	${dir}/builder/build/dev/debug/bin/amityd --stagenet --data-dir ${datadir}/n2 --p2p-bind-port 38080 --rpc-bind-port 38081 --zmq-rpc-bind-port 38082 --rpc-restricted-bind-port 38083 \
	--add-exclusive-node 127.0.0.1:28080 \
	--fixed-difficulty ${DIFF}  --block-sync-size 10
}

$1
