#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AMITY_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/helpers

detectos
detectversion

mkdir -p ${BUILDER_DIR}/build/release
cd ${BUILDER_DIR}/build/release
cmake -D CMAKE_BUILD_TYPE=release -D STATIC=ON -D BUILD_TAG="windows-x64" -D ARCH="x86-64" -G "MSYS Makefiles" ../../..
make -j4

zip -rj ${AMITY_DIR}/${REPO_NAME}-v${AMITY_VERSION}_windows-x64.zip ${BUILDER_DIR}/build/release/bin/*
